export const PRODUCT_STATUS = {
    ACTIVE: "ACTIVE",
    SOLD_OUT: "SOLD_OUT",
    VIOLATE: "VIOLATE",
    UNLISTED: "UNLISTED",
}

export const ORDER_STATUS = {
    CREATED: 'CREATED',
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    SHIPPED: 'SHIPPED',
    DELIVERED: 'DELIVERED',
    CANCELED: 'CANCELED',
}